var struct_z___construct___u_function___u_calendar_u_i_base___get_time___statics =
[
    [ "CalendarUIBase_eventGetTime_Parms", "struct_z___construct___u_function___u_calendar_u_i_base___get_time___statics_1_1_calendar_u_i_base__event_get_time___parms.html", null ]
];