var struct_z___construct___u_function___u_calendar_item_base___on_item_added___statics =
[
    [ "CalendarItemBase_eventOnItemAdded_Parms", "struct_z___construct___u_function___u_calendar_item_base___on_item_added___statics_1_1_calendar_85b001400a0e9514ec048ae55903fc5d.html", null ]
];