var struct_z___construct___u_function___u_task_a_p_i___set_browser_u_r_l___statics =
[
    [ "TaskAPI_eventSetBrowserURL_Parms", "struct_z___construct___u_function___u_task_a_p_i___set_browser_u_r_l___statics_1_1_task_a_p_i__event_set_browser_u_r_l___parms.html", null ]
];